# Generated by Django 4.0.1 on 2022-12-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('FASHION', 'Fashion'), ('SPORTS', 'Sports'), ('POLITICS', 'Politics'), ('FINANCE', 'Finance'), ('OTHERS', 'Others')], default='OTHERS', max_length=10),
        ),
    ]
